language: android
jdk: oraclejdk8

notifications:
  email: true

branches:
  only:
  - master

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-google-m2repository
  - extra-android-m2repository

licenses:
- 'android-sdk-preview-license-.+'
- 'android-sdk-license-.+'
- 'google-gdk-license-.+'

script:
  ./gradlew clean assembleDebug

deploy:
  provider: releases
  file_glob: true
  file: Application/build/outputs/apk/debug/*.ap
  skip_cleanup: true

  on:
    repo: tattatty/android-BasicMediaDecoder-master
    jdk: oraclejdk8
  api_key:    
    secure: "IPaotdPKBT9iAvBfEWbXd0jl7tDEjuDjMIleMTxhgUnt9IvrS7fzIKc+/TBy9USs7ZeOnODZXOfk3gi4aAmQU1RzGMFfM7TLpNgpSQCh5F1uCGSIApci67kwyG9rGfxjaNvqQYP4nj3i4G3MFTUSStHrijCHbogeCIYCop0GqhxTAh3z0ed7MZP+rGEQgJ+VucUKA7glgrfDRoZeZKX0sWSO3U0jSeBJIdrhcIi0lmWoen7EURKdShNapTTCWuR91G0n5pToOQbFnGr6wWhL4yrrL66DUMiSOGdhWnfvEip2QlWG6Sd+8M8zGZBfTy363dV3eFB+juAug71ptoOYJ4rymbxIs7hw3BqJB8dUqE3K0SQ+YjgGIKpV+0Pzj9gBHPaaUJ+RZDMruMZDHXmKhmh6+cGrLUDxr4QuYFP3U6wqibGSX2AAeA7M+oOTQFMgqbGE2d9DCE1swMPivI+Pjlb/iaHRRsbCdCd2vkfynHw4dd1sA0qQ8CD7gekklTysEj+Z6uNRF/h1yzFV7qyZNffxPhE68I2GY1g2J3HqgDBa8pRsWC0oc2w4CAHAQlan/5h71XqhNW2QV3N9Sgl8hl/r1gxP6J9Qu8gAajvGdQm8V1fzCDfm0GxApI2ySZBq58wqkTw4iSSxFYSqovKjwHQ7k5+XKxVlb3bTDpwUDpU="
