language: android


notifications:
  email: true

branches:
  only:
  - master

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-google-m2repository
  - extra-android-m2repository

licenses:
- 'android-sdk-preview-license-.+'
- 'android-sdk-license-.+'
- 'google-gdk-license-.+'

script:
  ./gradlew clean build

deploy:
  provider: releases
  user: "tat_tatty@hotmail.com"
  password: "aantmod131222"
  file_glob: true
  file: app/build/outputs/apk/*.apk
  skip_cleanup: true
  overwrite: true

  on:
    repo: tattatty/android-BasicMediaDecoder-master

  api_key:
    secure: 89847df54376bed816ee27eb230fd25452f39c2d
    
    
    
