language: android
jdk: oraclejdk8

notifications:
  email: true

branches:
  only:
  - master

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-google-m2repository
  - extra-android-m2repository

licenses:
- 'android-sdk-preview-license-.+'
- 'android-sdk-license-.+'
- 'google-gdk-license-.+'

script:
  ./gradlew clean build

deploy:
  provider: releases
  file_glob: true
  file: app/build/outputs/apk/*.apk
  skip_cleanup: true

  on:
    repo: tattatty/android-BasicMediaDecoder-master
    jdk: oraclejdk8
  api_key:
    secure: ${personal_token}
